<?php

/**
 * @file
 * Contains credly.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function credly_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the credly module.
    case 'help.page.credly':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is a third party integration of drupal with credly a badge allotment lms tool') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function credly_theme() {
  return [
    'credly' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_form_alter() on behalf of credly.module.
 */
function credly_form_user_login_form_alter(&$form, FormStateInterface $form_state, $form_id) {
    // Change form id here
    if ($form_id == 'user_login_form') {
        $form['#submit'][1] = 'credly_message_onlogin_handler';
    }
}

/**
 * Function for credly module user setting message.
 */
function credly_message_onlogin_handler(){
    drupal_set_message(t('Please provide login credentials for your credly account to display badge'), 'status');
}
